# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - "#3B3F4C"
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
  showFileTree: true
  showListFooter: false
  showRandomTip: false
  showBottomLine: false
  showCommandLog: true
  showIcons: true
  nerdFontsVersion: "3"
git:
  pagers: [{colorArg: always, pager: delta --dark --paging=never}]
disableStartupPopups: true
notARepository: create
os:
  edit: ~/.local/share/bob/nvim-bin/nvim {{filename}}
  editAtLine: ~/.local/share/bob/nvim-bin/nvim {{filename}}
keybinding:
  universal:
    scrollUpMain: '<c-p>'
    scrollDownMain: '<c-n>'
  files:
    commitChangesWithEditor: 'c'
    commitChanges: 'C'
